apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'NisargShah1410/dotnetcore-webapp'
spec:
  type: website
  lifecycle: production
  owner: NisargShah1410
