apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnetcore-webapp
  annotations:
    github.com/project-slug: NisargShah1410/dotnetcore-webapp
spec:
  type: website
  lifecycle: unknown
  owner: backstage
